name: Team awesome's approval workflow
on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-lastest
    
    steps:
      name: community-action
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Done be approved"
